version: 2
project_name: backstage-regask
builds:
  - id: bsr
    main: .
    binary: backstage-regask
    env: [CGO_ENABLED=0]
    goos: [darwin, linux]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X main.version={{.Version}}
archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
homebrew_casks:
  - name: backstage-regask
    repository:
      owner: regask
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/regask/backstage-cli"
    description: "Regask Backstage from your terminal"
checksum:
  name_template: "checksums.txt"
